### ISSUE TITLE
See that 1.6 got shipped to Stable, but having same issue as in 1.5

### ISSUE THREAD

**Issue by ThisByzantineConduit** [OMGDuke/SDH-GameThemeMusic#85] opened 2024-09-13 05:21 UTC
Tried every single instance on the new 1.6 release in Stable and all song search results populate and then disappear entirely leaving no options.

**Comment by OMGDuke** [comment] 2024-09-13 07:56
Duplicate of #84

**Closed** 2024-09-13 07:56 UTC

**Comment by CCWH68** [comment] 2024-09-14 14:18
Same issue for me.

**Comment by CCWH68** [comment] 2024-09-14 14:26
My steam deck is set  in french language. I've this issue since 2 ou 3 months. None of the updates (like 1.5+ or 1.6) were able to solve the problem.
