### ISSUE TITLE
Any plans for an offline music files option?

### ISSUE THREAD

**Issue by ThisByzantineConduit** [OMGDuke/SDH-GameThemeMusic#83] opened 2024-09-08 02:50 UTC
Love the online nature of the plug-in for changing songs on the fly and having music auto-assigned to new games, but for times when I'm away from WiFi or when the instances are spotty, it would be super nice to be able to set a default "fallback" song file which can still allow use of the online functionality simultaneously.

I'm not a dev like you so I know sometimes these seemingly simple features are actually very hard to implement, especially with a homebrew app on a semi-locked down platform. But I think many users would really appreciate this feature if you are able to make it work! Thanks so much for all your hard work.

**Comment by OMGDuke** [comment] 2024-09-09 07:59
Duplicate of #27

**Closed by OMGDuke** 2024-09-09 07:59 UTC
